### ISSUE TITLE
Change code pool to community

### ISSUE THREAD

**Issue by amenk** [tim-reynolds/magento-qconfig#1]
please :-)

**Comment by tim-reynolds** [comment]
Yup. Just realized that mistake. Facepalm. Inbound in a minute.

**Comment by tim-reynolds** [comment]
Fixed. Yeah, realized that when I started working to package it up for connect.

**Comment by amenk** [comment]
Somehwere somebody had an idea to convert modman definition files to Magento connect packages. But I do not know where this project went ... But this might save you some work.

**Comment by amenk** [comment]
You have to update the first line of the modman file :-)
