### ISSUE TITLE
Composer.json

### ISSUE THREAD

**Issue by amenk** [tim-reynolds/magento-qconfig#17]
I would like to create a composer file for you. Do you already have a https://packagist.org/ account? If not, it would be great if you create own to reserve your package prefix ...

**Comment by tim-reynolds** [comment]
Ok, I created an account. Now what should I do?

**Comment by amenk** [comment]
You can create a composer.json :-) Should be on the same level like the modman file.

timreynolds  should be replaced with the account name you registered.

Example:

<pre>
{
    "name": "timreynolds/magento-qconfig",
    "license": "OSL-3.0",
    "type": "magento-module",
    "description": ".........",
    "homepage": "http://www.example.com/",
    "require": {
        "magento-hackathon/magento-composer-installer": "*"
    },
    "authors":[
        {
            "name":"your name",
            "email":"yourmail@example.com"
        }
    ]
}
</pre>

**Comment by amenk** [comment]
What is you account name?

**Comment by tim-reynolds** [comment]
https://packagist.org/packages/tim-reynolds/magento-qconfig

Does this look right? 

Can't thank you enough for keeping on me for this. I get distracted so easily. Heck, the version of this on Connect is quite out of date at this point. Need to update that.

**Comment by amenk** [comment]
I hate Connect :-)
Packagist looks good.

No need for any thanks ...
you know, I do this all for myself - as I am a great fan of the plugin and want / need to install it via composer :-)
Open Source / Pull Requests are a big work-safer at the end of the day.

**Comment by tim-reynolds** [comment]
Someone had a repo where they had a composer script for pulling 'good' Magento modules all together, but I can't recall who had it or where it was. Any chance you remember? I thought it was controlled by Firegento but now I'm not sure.

**Comment by amenk** [comment]
http://packages.firegento.com/ ?

**Comment by tim-reynolds** [comment]
Probably, though that looks like it is indexing Connect, so an old version appears on it. About time I updated connect, I think. Wish there was an easier way heh.

**Comment by amenk** [comment]
The packages on connect a refered as connect20/... when installing - I think.
