### ISSUE TITLE
Reset search

### ISSUE THREAD

**Issue by amenk** [tim-reynolds/magento-qconfig#4]
There should be a function to reset the search (clear the current search / remove all the highlighting)
- by pressing the ESC key in the search box
- clicking a small button "x" (to be added)

**Comment by tim-reynolds** [comment]
Agreed. Wanted to get it out before I worked on the visual aspects. As a developer I like the ESC, but I gotta think about merchants. So, will probably go with the X

**Comment by amenk** [comment]
Sure, I am very happy that you got it out already :+1:

**Comment by amenk** [comment]
Why not implement both? The ESC shortcut and an X ?

**Comment by tim-reynolds** [comment]
Hmm. No reasonable argument against that!

**Comment by tim-reynolds** [comment]
Fixed.

**Comment by amenk** [comment]
I actually would remove the X if the field is empty. Because clicking on it if the field is empty does not have any effect, of course :-)
